config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', confirmations: 'confirmations' }
  root 'pages#index'
  resources :listings do
    resources :orders, only: [:new, :create]
  end
  resources :pages, only: [:index]
  get 'pages/about'

  get 'pages/contact'
  get 'vendor' => 'listings#vendor'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  has_many :orders
  validates :name, :description, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :name, uniqueness: true
  # validates :image_file_name, allow_blank: true, format: {
  #   with: %r{\.(gif|jpg|jpeg|png)\Z}i,
  #   message: 'Must be a url for a gif, jpg or png image file.'
  # }

   has_attached_file :image, styles: { medium: "250x250>", thumb: "100x100>" }, default_url: "missing.jpg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  #before_action :authenticate_user!, only: [:vendor, :new, :create, :update, :destroy]
  before_action :validate_user, only: [:edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def vendor
    #Basically saying we only want the listings of the current user
    @listings = Listing.where(user: current_user).order('created_at DESC')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def validate_user
      if current_user != @listing.user
        redirect_to root_path
         flash[:danger] =  'You can only alter your own listings'
      end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_display.html.erb
<h1 align='center'>Books</h1>
<% if user_signed_in? %>
  <h3><%= link_to 'New Listing', new_listing_path, class: 'btn btn-success' %></h3>
<% end %>



<div class="row center cust-row">
  <% @listings.each do |listing| %>
    <div class="col-md-3 cust-thumb">
      <div class="thumbnail ">
        <%= link_to image_tag(listing.image.url), listing  if listing.image?%>
        <div class="caption">
          <h3><%= listing.name %></h3>
          <p>
            <%= "$#{listing.price}" %><br>
          </p>

          <p>
            <%= "Listed by: #{listing.user.username} " %>
          </p>


            <% if (user_signed_in?) && (current_user == listing.user) %>
              <%= link_to 'Edit Listing', edit_listing_path(listing), class: 'btn btn-link' %> |
              <%= link_to 'Delete Listing', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

app/views/listings/_form.html.erb
<%= form_for(listing, html: { multipart: true }) do |f|   %>
  <% if listing.errors.any? %>
    <div id="error_explanation" >

      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class='form-group'>
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class: 'btn btn-link' %> |
<%= link_to 'Back', listings_path, class: 'btn btn-link' %>

app/views/listings/index.html.erb
<h1 align='center'>Listings</h1>
<br>

<div class="row center">
  <% @listings.each do |listing| %>
    <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(listing.image.url), listing %>
        <div class="caption">
          <h3><%= listing.name %></h3>
          <p>
            <%= "$#{listing.price}" %><br>
          </p>

          <p>
            <%= "Listed by: #{listing.user.username} " %>
          </p>


            <% if (user_signed_in?) && (current_user == listing.user) %>
              <%= link_to 'Edit', edit_listing_path(listing), class: 'btn btn-link' %>
              <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link' %>
            <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link' %>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path, class: 'btn btn-link' %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<div class='row'>
  <div class='col-md-6'>
    <div class='thumbnail'>
    <%= image_tag @listing.image.url %>
    </div>
  </div>
  <div class='col-md-6 cust-list'>
    <h3><%= @listing.name %></h3>
    <p><%= "$#{@listing.price}" %></p>
    <p><%= @listing.description %></p>
    <p><%= "Listed by: #{@listing.user.username}" %></p>
    <%= link_to 'Buy Now', new_listing_order_path(@listing), class: 'btn btn-primary ' %>

  </div>
</div>

<% if current_user == @listing.user %>
  <%= link_to 'Edit', edit_listing_path(@listing), class: 'btn btn-link' %> |
<% end %>
<%= link_to 'Back to listings', listings_path, class: 'btn btn-link' %>

app/views/listings/vendor.html.erb
<%= render 'display' %>