config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations', confirmations: 'confirmations' }
  root 'pages#index'
  resources :listings do
    resources :orders, only: [:new, :create]
  end
  resources :pages, only: [:index]
  get 'pages/about'

  get 'pages/contact'
  get 'vendor' => 'listings#vendor'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/common/_footer.html.erb
<div class="container">
  <footer class="footer">
    <p class='foot-left btn btn-link'><%= link_to 'Contact', pages_contact_path %></p>
    <small>
      Copyright &copy; BookBuy PTY LTD 2017
    </small>
    <p class='foot-right btn btn-link'><%= link_to 'About', pages_about_path %></p>
  </footer>
</div>

app/views/common/_nav.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "BookBuy", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to 'Books', listings_path %></li>

      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li> <%= link_to 'My Listings', vendor_path %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          <li><%= link_to 'Settings', edit_user_registration_path %></li>
          <% else %>
          <li><%= link_to 'Login', new_user_session_path %> </li>
          <li><%= link_to 'Signup', new_user_registration_path %> </li>
        <% end %>



      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>